export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const CATEGORIES = [
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Machine Learning",
  "DevOps",
  "Cloud Computing",
  "Cybersecurity",
  "Blockchain",
  "Game Development",
  "UI/UX Design",
] as const;

export const DIFFICULTIES = ["Beginner", "Intermediate", "Advanced"] as const;

export const TECH_STACKS = [
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "TypeScript",
  "JavaScript",
  "Go",
  "Rust",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Docker",
  "Kubernetes",
  "AWS",
  "GCP",
  "Azure",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "GraphQL",
  "REST API",
  "Tailwind CSS",
  "Supabase",
  "Firebase",
  "Prisma",
] as const;

export const HEAR_ABOUT_US_OPTIONS = [
  "Google Search",
  "YouTube",
  "Instagram",
  "Twitter / X",
  "LinkedIn",
  "Friend / Referral",
  "College / University",
  "Blog / Article",
  "Other",
] as const;

export const SITE_CONFIG = {
  name: "Code Hunters",
  tagline: "Hunt the Skills. Build the Future.",
  description:
    "Premium programming courses and ready-to-use developer projects. Learn from industry experts and build real-world applications.",
  url: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  ogImage: "/og-image.png",
  creator: "Code Hunters Team",
  keywords: [
    "programming courses",
    "developer projects",
    "learn to code",
    "web development",
    "full stack",
    "React",
    "Next.js",
    "TypeScript",
    "edtech",
    "online learning",
  ],
} as const;

export const REFERRAL_COINS_PER_PURCHASE = 15;
export const COINS_FOR_COUPON_THRESHOLD = 80;
export const COUPON_DISCOUNT_PERCENT = 20;
export const STUDENT_DISCOUNT_PERCENT = 20;
export const MAX_TOTAL_DISCOUNT_PERCENT = 30;
export const ZIP_DOWNLOAD_EXPIRY_SECONDS = 60;
